movieapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_index, name='index'),
    path('movies/', views.MovieListView.as_view(), name='movie-list'),
    path('movie/create/', views.MovieCreateView.as_view(), name= 'movie-create'),
    path('movie/update/<int:pk>', views.MovieUpdateView.as_view(), name='movie-update'),
    path('movie/detail/<int:pk>', views.MovieDetailView.as_view(), name='movie-detail'),
    path('movie/delete/<int:pk>', views.MovieDeleteView.as_view(), name='movie-delete'),
    path('director/', views.DirectorListView.as_view(), name='director-list'),
    path('director/create/', views.DirectorCreateView.as_view(), name='director-create'),
    path('director/update/<int:pk>', views.DirectorUpdateView.as_view(), name='director-update'),
    path('director/detail/<int:pk>', views.DirectorDetailView.as_view(), name='director-detail'),
    path('director/delete/<int:pk>', views.DirectorDeleteView.as_view(), name='director-delete'),
    path('studios/', views.StudioListView.as_view(), name='studio-list'),
    path('studio/create/', views.StudioCreateView.as_view(), name='studio-create'),
    path('studio/update/<int:pk>', views.StudioUpdateView.as_view(), name='studio-update'),
    path('studio/delete/<int:pk>', views.StudioDeleteView.as_view(), name='studio-delete'),
    path('studio/detail/<int:pk>', views.StudioDetailView.as_view(), name='studio-detail'),
    path('genres/', views.GenreListView.as_view(), name='genre-list'),
    path('genre/create/', views.GenreCreateView.as_view(), name='genre-create'),
    path('genre/update/<int:pk>', views.GenreUpdateView.as_view(), name='genre-update'),
    path('genre/delete/<int:pk>', views.GenreDeleteView.as_view(), name='genre-delete'),
    path('genre/detail/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
]

movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movieapp/', include('movieapp.urls')),
    path('', RedirectView.as_view(url='movieapp/')),
]

movieapp/models.py
from django.db import models
import uuid

class Movie(models.Model):
    title = models.CharField(max_length=200)
    prefix = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    director = models.ManyToManyField('Director')
    studio = models.ForeignKey('Studio',on_delete=models.CASCADE)
    released_date = models.DateField()
    cover_image = models.ImageField(upload_to='movieapp/static/images',null=True,blank=True)
    review = models.TextField(max_length=500)
    genre = models.ManyToManyField('Genre')
    asin = models.UUIDField(unique=True, default=uuid.uuid4)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

class Studio(models.Model):
    title = models.CharField(max_length=200)
    prefix = models.CharField(max_length=200)
    website = models.URLField(null=True, blank=True)
    slug = models.SlugField(max_length=200)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

class Genre(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    def __str__(self):
        """String for representing the Model object."""
        return self.title

class Director(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    middle_name = models.CharField(max_length=200)
    phone = models.CharField(max_length=12)
    website = models.URLField(null=True, blank=True)
    birthday = models.DateField()
    GENDER = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER,
        blank=True,
        help_text='gender',
    )
    def __str__(self):
        """String for representing the Model object."""
        return self.first_name

movieapp/views.py
from django.shortcuts import render
from .models import Movie, Director, Studio, Genre
from django_filters import views
from django.views import generic
from django.urls import reverse_lazy
import os

def show_index(request):
    context = {
        'total_movie': Movie.objects.all().count(),
        'total_directors': Director.objects.all().count(),
        'total_studio': Studio.objects.all().count(),
        'total_genre': Genre.objects.all().count(),
    }
    return render(request, 'movieapp/index.html', context)

class MovieListView(views.FilterView):
    model = Movie
    filterset_fields = ['title','director','studio','released_date','genre','asin']

class MovieCreateView(generic.CreateView):
    model = Movie
    fields = ['title','prefix','subtitle','slug','director','studio','released_date','genre','cover_image','review','asin']
    success_url = reverse_lazy('movie-list')

class MovieUpdateView(generic.UpdateView):
    model = Movie
    fields = ['title', 'prefix', 'subtitle', 'slug', 'director', 'studio', 'released_date', 'genre', 'cover_image',
              'review', 'asin']
    success_url = reverse_lazy('movie-list')

class MovieDetailView(generic.DetailView):
    model = Movie

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        obj = Movie.objects.get(pk=self.kwargs.get('pk'))
        image = obj.cover_image.name
        image = os.path.basename(image)
        image = 'images'+'//'+image
        context['image_name'] = image
        return context

class MovieDeleteView(generic.DeleteView):
    model = Movie
    success_url = reverse_lazy('movie-list')

class DirectorListView(views.FilterView):
    model = Director
    filterset_fields = ['first_name','middle_name','last_name','phone','website','birthday','gender']

class DirectorCreateView(generic.CreateView):
    model = Director
    fields = ['first_name','middle_name','last_name','phone','website','birthday','gender']
    success_url = reverse_lazy('director-list')

class DirectorUpdateView(generic.UpdateView):
    model = Director
    fields = ['first_name', 'middle_name', 'last_name', 'phone', 'website', 'birthday', 'gender']
    success_url = reverse_lazy('director-list')

class DirectorDetailView(generic.DetailView):
    model = Director

class DirectorDeleteView(generic.DeleteView):
    model = Director
    success_url = reverse_lazy('director-list')

class StudioListView(views.FilterView):
    model = Studio
    filterset_fields = ['title','prefix','website','slug']

class StudioCreateView(generic.CreateView):
    model = Studio
    fields = ['title','prefix','website','slug']
    success_url = reverse_lazy('studio-list')

class StudioUpdateView(generic.UpdateView):
    model = Studio
    fields = ['title', 'prefix', 'website', 'slug']
    success_url = reverse_lazy('studio-list')

class StudioDeleteView(generic.DeleteView):
    model = Studio
    success_url = reverse_lazy('studio-list')

class StudioDetailView(generic.DetailView):
    model = Studio

class GenreListView(views.FilterView):
    model = Genre
    filterset_fields = ['title','slug']

class GenreCreateView(generic.CreateView):
    model = Genre
    fields = ['title','slug']
    success_url = reverse_lazy('genre-list')

class GenreUpdateView(generic.UpdateView):
    model = Genre
    fields = ['title','slug']
    success_url = reverse_lazy('genre-list')

class GenreDeleteView(generic.DeleteView):
    model = Genre
    success_url = reverse_lazy('genre-list')

class GenreDetailView(generic.DetailView):
    model = Genre

movieapp/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Book</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg" style="background-color: darkslategray;">
          <a class="navbar-brand" style="color: deeppink" href="{% url 'index' %}">Movie</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" style="color: deeppink" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color: deeppink" href="{% url 'movie-list' %}">Movies</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color: deeppink" href="{% url 'studio-list' %}">Studios</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" style="color: deeppink" href="{% url 'director-list' %}">Directors</a>
              </li>
                <li class="nav-item">
                <a class="nav-link" style="color: deeppink" href="{% url 'genre-list' %}">Genres</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
<div>
  <div class="container-fluid">
    <div class="row" >
      <div class="col-sm-2 pt-3" style="background-color:teal">
        <ul class="sidebar-nav" style="list-style-type: none;" >
          <li><a class= "" style="color: deeppink;" href="{% url 'movie-create' %}">Create Movie</a></li>
          <li><a class= "" style="color: deeppink;" href="{% url 'studio-create' %}">Create Studio</a></li>
            <li><a class= "" style="color: deeppink;" href="{% url 'genre-create' %}">Create Genre</a></li>
            <li><a class= "" style="color: deeppink;" href="{% url 'director-create' %}">Create Director</a></li>
        </ul>
      </div>
      <div class="col-sm-10">{% block content %} {% endblock %}
      </div>
    </div>
  </div>
</div>
</body>
</html>
</body>
</html>

movieapp/templates/movieapp/director_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1>Movie Delete</h1>
    <p>Are you sure you want to delete "{{ object }}" director?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

movieapp/templates/movieapp/director_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
  <button style="border-radius: 50%;border-color: black;" disabled>
    <a href="{% url 'director-list' %}">
    <i class="fa fa-arrow-left" onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" ></i>
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'director-delete' director.id %}" style="text-decoration: none;">Delete
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'director-update' director.id %}" style="text-decoration: none;">Update
    </a>
  </button>
  <br><br>
  <h3>Director Detail</h3>
  <p><strong>First Name: </strong>{{ director.first_name }}</p>
  <p><strong>Last Name: </strong>{{ director.middle_name }}</p>
  <p><strong>Middle Name: </strong>{{ director.last_name }}</p>
  <p><strong>Phone: </strong>{{ director.phone }}</p>
  <p><strong>Website: </strong>{{ director.website }}</p>
  <p><strong>Birthday: </strong>{{ director.birthday }}</p>
  <p><strong>Movie: </strong></p>
    {% if director.movie_set.all %}
      <ul>
        {% for movie in director.movie_set.all %}
          <li>{{ movie }}</li>
        {% endfor %}
      </ul>
    {% else %}
      No movie by this director
    {% endif %}
  </p>

{% endblock %}

movieapp/templates/movieapp/director_filter.html
{% extends "base_generic.html" %}

{% block content %}
    <button class="mybutton" onclick="location.href='{% url 'director-create' %}"><a href="{% url 'director-create' %}">Create Director</a></button>
    <h1>Filter</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    <h1>Director List:</h1>
    {% if object_list %}
          <table style="width:100%">
            {% for director in object_list %}
            <tr>
              <th style="text-align: center;"><a class="mylist-ele" href="{% url 'director-detail' director.id %}">{{ director }}</a></th>
              <th><button class="mybutton" onclick="location.href='{% url 'director-delete' director.id %}"><a href="{% url 'director-delete' director.id %}">Delete</a></button></th>
              <th><button class="mybutton" onclick="location.href='{% url 'director-update' director.id %}"><a href="{% url 'director-update' director.id %}">Update</a></button></th>
            </tr>
            {% endfor %}
          </table>
          {% else %}
            <p>There are no director in this app.</p>
          {% endif %}

{% endblock %}

movieapp/templates/movieapp/director_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Director</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

movieapp/templates/movieapp/genre_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1>Genre Delete</h1>
    <p>Are you sure you want to delete "{{ object }}" genre?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

movieapp/templates/movieapp/genre_filter.html
{% extends "base_generic.html" %}

{% block content %}
    <button class="mybutton" onclick="location.href='{% url 'genre-create' %}';"><a href="{% url 'genre-create' %}">Create Genre</a></button>
    <h1>Filter</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    <h1>Genre List:</h1>
    {% if object_list %}
          <table style="width:100%">
            {% for genre in object_list %}
            <tr>
              <th style="text-align: center;"><a class="mylist-ele" href="{% url 'genre-detail' genre.id %}">{{ genre }}</a></th>
              <th><button class="mybutton" onclick="location.href='{% url 'genre-delete' genre.id %}';"><a href="{% url 'genre-delete' genre.id %}">Delete</a></button></th>
              <th><button class="mybutton" onclick="location.href='{% url 'genre-update' genre.id %}';"><a href="{% url 'genre-update' genre.id %}">Update</a></button></th>
            </tr>
            {% endfor %}
          </table>
          {% else %}
            <p>There are no genres in this app.</p>
          {% endif %}

{% endblock %}

movieapp/templates/movieapp/genre_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Genre</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}

movieapp/templates/movieapp/index.html
{% extends "base_generic.html" %}

{% block content %}

    <h1><strong>BookApp Summary:</strong></h1>
    <br>
    <h5><strong>Total Movies :</strong> {{ total_movie }}</h5>
    <h5><strong>Total Directors :</strong> {{ total_directors }}</h5>
    <h5><strong>Total Studios :</strong> {{ total_studio }}</h5>
    <h5><strong>Total Genres :</strong> {{ total_genre }}</h5>


{% endblock %}

movieapp/templates/movieapp/movie_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1>Movie Delete</h1>
    <p>Are you sure you want to delete "{{ object }}" publisher?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

movieapp/templates/movieapp/movie_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
  <button style="border-radius: 50%;border-color: black;" disabled>
    <a href="{% url 'movie-list' %}">
    <i class="fa fa-arrow-left" onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" ></i>
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'movie-delete' movie.id %}" style="text-decoration: none;">Delete
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'movie-update' movie.id %}" style="text-decoration: none;">Update
    </a>
  </button>
  <br><br>
  <h3>Movie Detail</h3>
  <p><strong>Title: </strong>{{ movie.title }}</p>
  <p><strong>Prefix: </strong>{{ movie.prefix }}</p>
  <p><strong>Subtitle: </strong>{{ movie.subtitle }}</p>
  <p><strong>Slug: </strong>{{ movie.slug }}</p>
  <p><strong>Director: </strong></p>
    {% if movie.director.all %}
      <ul>
        {% for director in movie.director.all %}
          <li>{{ director }}</li>
        {% endfor %}
      </ul>
    {% else %}
      No director for this movie
    {% endif %}
  </p>
  <p><strong>Studio: </strong>{{ movie.studio }}</p>
  <p><strong>Released Date: </strong>{{ movie.released_date }}</p>
  <p><strong>cover_image: </strong><img src="{% static image_name %}" width="50%" height="50%"></p></p>
  <p><strong>Review: </strong>{{ movie.review }}</p>
  <p><strong>Genre: </strong></p>
    {% if movie.genre.all %}
      <ul>
        {% for genre in movie.genre.all %}
          <li>{{ genre }}</li>
        {% endfor %}
      </ul>
    {% else %}
      No genre for this movie
    {% endif %}
  </p>
  <p><strong>ASIN: </strong>{{ movie.asin }}</p>


{% endblock %}

movieapp/templates/movieapp/studio_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <h1>Studio Delete</h1>
    <p>Are you sure you want to delete "{{ object }}" studio?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

movieapp/templates/movieapp/studio_detail.html
{% extends "base_generic.html" %}

{% block content %}
{% load static %}
  <button style="border-radius: 50%;border-color: black;" disabled>
    <a href="{% url 'studio-list' %}">
    <i class="fa fa-arrow-left" onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" ></i>
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'studio-delete' studio.id %}" style="text-decoration: none;">Delete
    </a>
  </button>
  <button style="border-color: black;" disabled>
    <a onmouseover = "this.style.color = 'black'" onmouseout = "this.style.color = 'blue'" href="{% url 'studio-update' studio.id %}" style="text-decoration: none;">Update
    </a>
  </button>
  <br><br>
  <h3>Studio Detail</h3>
  <p><strong>Title: </strong>{{ studio.title }}</p>
  <p><strong>Prefix: </strong>{{ studio.prefix }}</p>
  <p><strong>Website: </strong>{{ studio.website }}</p>
  <p><strong>Slug: </strong>{{ studio.slug }}</p>
  <p><strong>Movies: </strong></p>
    {% if studio.movie_set.all %}
      <ul>
        {% for movie in studio.movie_set.all %}
          <li>{{ movie }}</li>
        {% endfor %}
      </ul>
    {% else %}
      No movie by this studio
    {% endif %}
  </p>

{% endblock %}

movieapp/templates/movieapp/studio_filter.html
{% extends "base_generic.html" %}

{% block content %}
    <button class="mybutton" onclick="location.href='{% url 'studio-create' %}';"><a href="{% url 'studio-create' %}">Create Studio</a></button>
    <h1>Filter</h1>
    <form method="get">
        <table>
        {{ filter.form.as_table }}
        </table>
        <input type="submit" />
    </form>
    <h1>Studio List:</h1>
    {% if object_list %}
          <table style="width:100%">
            {% for studio in object_list %}
            <tr>
              <th style="text-align: center;"><a class="mylist-ele" href="{% url 'studio-detail' studio.id %}">{{ studio }}</a></th>
              <th><button class="mybutton" onclick="location.href='{% url 'studio-delete' studio.id %}';"><a href="{% url 'studio-delete' studio.id %}">Delete</a></button></th>
              <th><button class="mybutton" onclick="location.href='{% url 'studio-update' studio.id %}';"><a href="{% url 'studio-update' studio.id %}">Update</a></button></th>
            </tr>
            {% endfor %}
          </table>
          {% else %}
            <p>There are no studio in this app.</p>
          {% endif %}

{% endblock %}

movieapp/templates/movieapp/studio_form.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Studio</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}